#!/usr/bin/env bash

# for docs visit https://herbstluftwm.org/object-doc.html

hc() {
  herbstclient "$@"
}

hc emit_hook reload

# X11 stuff
# setxkbmap -layout us,ara -option 'grp:alt_shift_toggle'
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
xsetroot -solid '#0D0E15'
xwallpaper --zoom ~/media/pics/wallpapers/21.png
# xres_manage gen
# xres_manage load
# xmodmap ~/.config/x11/xmodmap.d/$(hostnamectl hostname)
$XDG_CONFIG_HOME/x11/xres/load
$XDG_CONFIG_HOME/x11/xmodmap/load

xset m 20/10 10
xset r rate 300 30
xset b on
# screen saver and dpms
xset s blank
xset s on
xset s 300 300
# xset s noexpose
xset dpms 300 0 0

# wmname LG3D
numlockx on

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Super

# hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close

hc keybind $Mod-Return spawn term launch
# hc keybind $Mod-Shift-Prior spawn env TERM=xst-256color term zoom 1
# hc keybind $Mod-Shift-Next spawn env TERM=xst-256color term zoom -1
hc keybind $Mod-d spawn rofi -show drun
hc keybind $Mod-e spawn $FM
hc keybind $Mod+KP_Enter spawn $FM trash:///
hc keybind Print spawn $SCREENSHOT clip
hc keybind $Mod-Escape spawn $SCREENSHOT clip
hc keybind $Mod-Shift-Escape spawn $COLOR_PICKER
hc keybind $Mod-grave spawn $SCREENSHOT clip
hc keybind $Mod-l spawn loginctl lock-session $XDG_SESSION_ID
hc keybind $Mod-backslash spawn scratchpad.hlwm

hc keybind $Mod-z spawn wm_control -t
hc keybind $Mod-x spawn wm_control -d

hc keybind $Mod+KP_Add spawn wm_control -au
hc keybind $Mod+KP_Subtract spawn wm_control -ad
hc keybind XF86AudioRaiseVolume spawn wm_control -au
hc keybind XF86AudioLowerVolume spawn wm_control -ad

hc keybind $Mod-Shift-KP_Add spawn wm_control -bu
hc keybind $Mod-Shift-KP_Subtract spawn wm_control -bd
hc keybind XF86MonBrightnessUp spawn wm_control -bu
hc keybind XF86MonBrightnessDown spawn wm_control -bd


# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
# hc keybind $Mod-h     focus left
# hc keybind $Mod-j     focus down
# hc keybind $Mod-k     focus up
# hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Control-Left  shift left
hc keybind $Mod-Control-Down  shift down
hc keybind $Mod-Control-Up    shift up
hc keybind $Mod-Control-Right shift right
# hc keybind $Mod-Control-h     shift left
# hc keybind $Mod-Control-j     shift down
# hc keybind $Mod-Control-k     shift up
# hc keybind $Mod-Control-l     shift right

# splitting frames
# create an empty frame at the specified direction
# hc keybind $Mod-u       split   bottom  0.5
# hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
# hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
# resizestep=0.02
# hc keybind $Mod-Control-h       resize left +$resizestep
# hc keybind $Mod-Control-j       resize down +$resizestep
# hc keybind $Mod-Control-k       resize up +$resizestep
# hc keybind $Mod-Control-l       resize right +$resizestep
# hc keybind $Mod-Control-Left    resize left +$resizestep
# hc keybind $Mod-Control-Down    resize down +$resizestep
# hc keybind $Mod-Control-Up      resize up +$resizestep
# hc keybind $Mod-Control-Right   resize right +$resizestep


hc set frame_border_active_color '#00000000'
hc set frame_border_normal_color '#00000000'
hc set frame_bg_normal_color '#00000000'
hc set frame_bg_active_color '#00000000'
hc set frame_border_width 0
hc set frame_bg_transparent on
# hc set frame_transparent_width 1
hc set frame_gap 0
hc set show_frame_decorations 'focused_if_multiple'

hc set window_gap 4
hc set frame_padding 20
hc set focus_stealing_prevention off
hc set auto_detect_monitors
hc set focus_follows_mouse 1
hc set hide_covered_windows on
hc set default_frame_layout horizontal
hc set tree_style '╾│ ├└╼─┐'

# hc set wmname LG3D

# hc set hide_covered_windows on
# hc set gapless_grid off
# hc set frame_active_opacity 50
# hc set mouse_recenter_gap 0
# hc set smart_window_surroundings off
# hc set smart_frame_surroundings on

hc set_layout horizontal


# tags
tag_names=( 1 2 3 4 5 6 )
tag_keys=( 1 2 3 4 5 6 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if [ -n "$key" ] ; then
    hc keybind "$Mod-$key" use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done

# cycle through tags
hc keybind $Mod-Shift-Right use_index +1 --skip-visible
hc keybind $Mod-Shift-Left  use_index -1 --skip-visible
# hc keybind $Mod-Shift-Right use_index +1 --skip-visible\
#   . wm_control -d
# hc keybind $Mod-Shift-Left  use_index -1 --skip-visible\
#   . wm_control -d

# layouting
hc keybind $Mod-r remove
# hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-w set_attr clients.focus.floating toggle
# hc keybind $Mod-d set_attr clients.focus.decorated toggle
# hc keybind $Mod-m set_attr clients.focus.minimized true
# hc keybind $Mod-Shift-m jumpto last-minimized
# hc keybind $Mod-p pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space\
  or , and . compare tags.focus.curframe_wcount = 2\
  . cycle_layout +1 vertical horizontal max vertical grid\
  , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

hc attr focus.decorated toggle
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# hc attr theme.title_height 13
# hc attr theme.title_when always
# hc attr theme.title_font 'Terminus:pixelsize=10'
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
# hc attr theme.title_depth 3  # space below the title's baseline
# hc attr theme.active.color '#345F0Cef'
# hc attr theme.title_color '#ffffff'
# hc attr theme.normal.color '#323232dd'
# hc attr theme.urgent.color '#7811A1dd'
# hc attr theme.tab_color '#1F1F1Fdd'
# hc attr theme.active.tab_color '#2B4F0Add'
# hc attr theme.active.tab_outer_color '#6C8257dd'
# hc attr theme.active.tab_title_color '#ababab'
# hc attr theme.normal.title_color '#898989'
# hc attr theme.inner_width 1
# hc attr theme.inner_color black
hc attr theme.border_width 0
# hc attr theme.floating.border_width 4
# hc attr theme.floating.outer_width 1
# hc attr theme.floating.outer_color black
# hc attr theme.active.inner_color '#789161'
# hc attr theme.urgent.inner_color '#9A65B0'
# hc attr theme.normal.inner_color '#606060'

# copy inner color to outer_color
# for state in active urgent normal ; do
#   hc substitute C theme.${state}.inner_color \
#   attr theme.${state}.outer_color C
# done

# hc attr theme.tiling.outer_width 1
# hc attr theme.background_color '#141414'


# rules
# for docs visit https://herbstluftwm.org/herbstluftwm.html#RULES
#
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
# hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floatplacement=center
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class='zoom' floating=on
# hc rule class='jetbrains-idea-ce' floating=on
hc rule class='kooha' floating=on
hc rule class='simple_droidcam_client' floating=on
hc rule class='adwaita-steam-gtk' floating=on
hc rule class='Rustdesk' floating=on
hc rule fixedsize floating=on
hc rule windowrole='About' floating=on
hc rule windowrole='Windscribe2' floating=on
# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#   # start it on each monitor
#   "$panel" "$monitor" &
# done

launch_once() {
  local pname="$1"
  shift
  local cmd="$@"

  if ! pgrep -x "$pname" >/dev/null; then
    $cmd &
  fi
}

# launch_once lxpolkit      lxpolkit
launch_once xss-lock      xss-lock lock
launch_once wired         wired
launch_once udiskie       udiskie -asm nested
launch_once stalonetray   stalonetray -t --geometry 1x1+1+1 --grow-gravity NW --icon-size 16 --slot-size 20 --icon-gravity E --kludges force_icons_size
launch_once nm-applet     nm-applet
launch_once parcellite    parcellite
launch_once thunar        thunar --daemon
# launch_once unclutter     unclutter --timeout 3 --jitter 10 --ignore-scrolling
launch_once shortsig      shortsig
launch_once jellyfin      /usr/lib/jellyfin/bin/jellyfin --webdir=/usr/share/jellyfin/web
launch_once syncthing     syncthing serve --no-browser --no-restart --logflags=0
# launch_once barriers      barriers -f -c .config/barrier/config.conf --disable-crypto
launch_once alttab        alttab -w 1 -d 2 -t 256x128 -i 48x48 -bg '#0D0E15' -fg '#F1F7ED' -frame '#F1F7ED' -inact '#294374' -font 'xft:Terminus'
launch_once syncthing-gtk syncthing-gtk -m

# pgrep lxpolkit || lxpolkit &
# pgrep xss-lock || xss-lock lock &
# pgrep wired || wired &
# pgrep udiskie || udiskie -asm nested &
#
# # pgrep stalonetray || stalonetray --dockapp-mode simple --icon-size 12 --slot-size 20 --window-type desktop -t
# pgrep stalonetray || stalonetray -t --geometry 1x1+1+1 --grow-gravity NW --icon-size 16 --slot-size 20 --icon-gravity E --kludges force_icons_size &
# pgrep nm-applet || nm-applet &
# pgrep parcellite || parcellite &
#
# # pgrep flashfocus || flashfocus -s &
# # pgrep picom || picom &
# pgrep thunar || thunar --daemon &
# pgrep unclutter || unclutter --timeout 3 --jitter 10 --ignore-scrolling &
#
# pgrep shortsig || shortsig &
# pgrep jellyfin || /usr/lib/jellyfin/bin/jellyfin --webdir=/usr/share/jellyfin/web &
# pgrep syncthing || syncthing serve --no-browser --no-restart --logflags=0 &
# pgrep barriers || barriers -f -c .config/barrier/config.conf --disable-crypto &
#
# pgrep alttab || alttab -w 1 -d 2 -t 256x128 -i 48x48 -bg '#0D0E15' -fg '#F1F7ED' -frame '#F1F7ED' -inact '#294374' -font 'xft:Terminus' &


hc set window_border_active_color `xgetres .fg`
hc set window_border_urgent_color `xgetres .color11`
hc set window_border_width 1
