format = "$username$directory$status$character"

add_newline = false

[character]
success_symbol = "[|](bold purple)"
error_symbol = "[!](bold red)"
vicmd_symbol = "[:](bold green)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "blue"
read_only = " [ro]"
read_only_style = "red"
truncation_length =	8
truncate_to_repo = false
truncation_symbol = "…/"

[username]
format = "[$user]($style) "
style_user = "white bold"
style_root = "red"
show_always = true

[status]
format = "[$status]($style)"
style = "bold red"
disabled = false

[git_status]
format = "[$all_status$ahead_behind]($style)"
ahead = "↑${count}"
diverged = "↑${ahead_count}↓${behind_count}"
behind = "↓${count}"
conflicted = "↕"
untracked = "?"
stashed = "#"
modified = "!"
staged = "+"
renamed = "r"
deleted = "d"
style = "bold red"
