#!/bin/sh

userresources=$XDG_CONFIG_HOME/x11/Xresources
usermodmap=$XDG_CONFIG_HOME/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# twm &
# xclock -geometry 50x50-1+1 &
# xterm -geometry 80x50+494+51 &
# xterm -geometry 80x20+494-0 &
# exec xterm -geometry 80x66+0+0 -name login


eval $(ssh-agent)

# run /etc/X11/xinitrc.d scripts
# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#   [ -x "$f" ] && . "$f"
#  done
#  unset f
# fi

# fix whatever this is
# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# dex -a
# exec bspwm

exec herbstluftwm --locked
# exec firefox
# exec dwm
# exec startxfce4
# exec leftwm
# exec debus-launch leftwm

# compiz

# exec firefox

# xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto

# exec i3

# sxhkd &

# exec startplasma-x11


# export XDG_SESSION_TYPE=x11
# export GDK_BACKEND=x11
# exec gnome-session

# exec dwm

#exec chamfer --config=/usr/share/chamfer/config/config.py --shader-path=/usr/share/chamfer/shaders/

# wingpanel &
# plank &
# exec gala


# exec dbus-launch --exit-with-session bspwm

# exec /usr/bin/spectrwm
